name: Build and Push Docker Image on Release
on:
 push:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v4

      # 2️⃣ Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Build and push the Docker image
      - name: Build and push Docker image
        run: |
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          echo "GitHub Prod"
          docker build . \
            --file Dockerfile_prod \
            --tag ghcr.io/${REPO_LOWER}/nopayloaddb:prod
          docker push ghcr.io/${REPO_LOWER}/nopayloaddb:prod
          echo "GitHub Dev"
          docker build . \
            --file Dockerfile \
            --tag ghcr.io/${REPO_LOWER}/nopayloaddb:dev
          docker push ghcr.io/${REPO_LOWER}/nopayloaddb:dev
          